services:
  my-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  my-node:
    image: "node:12.18.1"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/app
    links:
      - my-db
    command: "npm run pets"
    #command: "npm run dev"
